package flt.polynomialInterpreter.parser;

/** Interface generated by CUP using symbol constants **/
public interface sym {
	/* terminals */
	//eof & error
	public static final int EOF = 0;
	public static final int error = 1;
	//polynomial components
	//polynomial variable
	public static final int POL_VAR = 2;
	//general unknown
	public static final int TERMX = 3;
	//power operator
	public static final int POWER_OP = 4;
	//symbols for binary operations
	public static final int PLUS = 5;
	public static final int MINUS = 6;
	public static final int TIMES = 7;
	public static final int DIVIDE = 8;
	//unary operators
	public static final int DIFFERENTIAL = 9;
	public static final int INTEGRAL = 10;
	//brakcets for separating operations
	public static final int LBRACKET = 11;
	public static final int RBRACKET = 12;
	//assignment operator
	public static final int EQUAL = 13;
	//variable for assigning the result
	public static final int VAR = 14;
	//free term, multiplication coefficient 
	public static final int NUMBER = 15;
	//row end signal
	public static final int SEMI = 16;
}
