package flt.polynomialInterpreter.parser;

/** Interface generated by CUP using symbol constants **/
public interface sym {
	/* terminals */
	public static final int EOF = 0;
	public static final int error = 1;
	public static final int POL_VAR = 2;
	public static final int TERMX = 3;
	public static final int POWER_OP = 4;
	public static final int PLUS = 5;
	public static final int MINUS = 6;
	public static final int TIMES = 7;
	public static final int DIVIDE = 8;
	public static final int DIFFERENTIAL = 9;
	public static final int INTEGRAL = 10;
	public static final int LBRACKET = 11;
	public static final int RBRACKET = 12;
	public static final int NUMBER = 13;
	public static final int SEMI = 14;
}
