
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat May 26 13:45:57 EEST 2012
//----------------------------------------------------

package flt.polynomialInterpreter.parser;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int TIMES = 5;
  public static final int PLUS = 3;
  public static final int EQUAL = 10;
  public static final int SEMI = 2;
  public static final int LBRACKET = 7;
  public static final int RBRACKET = 8;
  public static final int POWER_OP = 9;
  public static final int DIFFERENTIAL = 12;
  public static final int EOF = 0;
  public static final int NUMBER = 14;
  public static final int DIVIDE = 6;
  public static final int INTEGRAL = 11;
  public static final int MINUS = 4;
  public static final int error = 1;
  public static final int TERMX = 17;
  public static final int MODE = 13;
  public static final int POL_VAR = 15;
  public static final int VAR = 16;
}

